table Dim_Region
	lineageTag: 5fe1b65b-4b71-46d0-883b-f58b77c852e2

	column level_type
		dataType: string
		lineageTag: 44e5d739-2617-4589-b291-ab8b213b0a66
		summarizeBy: none
		sourceColumn: level_type

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: b7a94909-1e3e-47a0-9317-b97bb427e1bf
		summarizeBy: none
		sourceColumn: sort_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: 58ff02fe-9d6b-4ba9-aae6-e6a6a4089c88
		summarizeBy: none
		sourceColumn: region_id

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column region_source
		dataType: string
		lineageTag: 93838865-3e68-4cc4-b834-6ac692cce465
		summarizeBy: none
		sourceColumn: region_source

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: e242dbd4-a4cf-447f-ac00-7caeff8c7475
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: region
		sortByColumn: sort_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Dim_Region = m
		mode: import
		source =
				let
				    Source = Parquet.Document(Web.Contents(AzuriteBaseUrl & "dim_region/data.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"region", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

