# Script to clean up local staging data generated by Spark.
# Use this to clear "garbage" before a fresh ETL run.
# NOTE: This does NOT delete data/raw (GUS source files).

$projectRoot = Resolve-Path "$PSScriptRoot\.."
$stagingPath = Join-Path $projectRoot "data\staging"

Write-Host "--- CLEANUP TOOL ---" -ForegroundColor Cyan

# 1. Clean Staging Data (Parquet files destined for Azurite)
if (Test-Path $stagingPath) {
    Write-Host "Removing staging data at: $stagingPath" -ForegroundColor Yellow
    Remove-Item -Path $stagingPath -Recurse -Force
    Write-Host "   [OK] Staging directory cleaned." -ForegroundColor Green
} else {
    Write-Host "   [INFO] Staging directory is already empty." -ForegroundColor Gray
}

# 2. Optional: Clean Logs (Uncomment if you want to clean logs too)
# $logsPath = Join-Path $projectRoot "logs"
# if (Test-Path $logsPath) {
#     Remove-Item -Path "$logsPath\*.log" -Force
#     Write-Host "   [OK] Logs cleaned." -ForegroundColor Green
# }

Write-Host "Cleanup finished. You are ready for a clean run." -ForegroundColor Green